/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ifndb;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Reale
 */
public class FrameOrdini extends javax.swing.JFrame {

    /**
     * Creates new form FrameOrdiniperCliente
     */
    
    public FrameOrdini() {
        initComponents();
        try {
            IFNDB.recoverFilterOrders(FilterCombo);
            IFNDB.recoverClientiCombo(IdClienteCombo);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdClienteCombo = new javax.swing.JComboBox<>();
        FilterCombo = new javax.swing.JComboBox<>();
        BTNVisualizza = new javax.swing.JButton();
        BTNElimina = new javax.swing.JButton();
        IdclienteLB1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ClienteCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordini");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(958, 691));

        IdClienteCombo.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        IdClienteCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        IdClienteCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IdClienteComboMouseClicked(evt);
            }
        });
        IdClienteCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdClienteComboActionPerformed(evt);
            }
        });

        FilterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Discendente" }));
        FilterCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilterComboMouseClicked(evt);
            }
        });
        FilterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterComboActionPerformed(evt);
            }
        });

        BTNVisualizza.setBackground(new java.awt.Color(0, 153, 255));
        BTNVisualizza.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BTNVisualizza.setForeground(new java.awt.Color(255, 255, 255));
        BTNVisualizza.setText("Visualizza");
        BTNVisualizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVisualizzaActionPerformed(evt);
            }
        });

        BTNElimina.setBackground(new java.awt.Color(204, 0, 0));
        BTNElimina.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BTNElimina.setForeground(new java.awt.Color(255, 255, 255));
        BTNElimina.setText("Elimina");
        BTNElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminaActionPerformed(evt);
            }
        });

        IdclienteLB1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        IdclienteLB1.setText("Ordina per:");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        table.setAutoCreateRowSorter(true);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OrderID", "CustomerID", "EmployeeID", "OrderDate"
            }
        ));
        table.setEditingRow(-1);
        table.setMaximumSize(new java.awt.Dimension(2147483647, 90));
        table.setShowGrid(true);
        jScrollPane1.setViewportView(table);

        ClienteCheck.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        ClienteCheck.setText("Filtra Cliente:");
        ClienteCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdClienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClienteCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdclienteLB1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNElimina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNVisualizza))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNElimina)
                    .addComponent(BTNVisualizza))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(IdclienteLB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClienteCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdClienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FilterComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilterComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FilterComboMouseClicked

    private void BTNEliminaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BTNEliminaActionPerformed
        // TODO add your handling code here:
        String t = (String) FilterCombo.getSelectedItem();
        IFNDB.deleteOrders(table);
        try{
            IFNDB.showOrders((String)IdClienteCombo.getSelectedItem(), t, table, ClienteCheck.isSelected());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Errore nella eliminazione");
        }
        

    }// GEN-LAST:event_BTNEliminaActionPerformed

    private void BTNOrdinaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BTNOrdinaActionPerformed
        //
        try {
            IFNDB.recoverFilterOrders(FilterCombo);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }// GEN-LAST:event_BTNOrdinaActionPerformed

    private void IdClienteComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_IdClienteComboActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_IdClienteComboActionPerformed

    private void BTNVisualizzaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BTNVisualizzaActionPerformed
        // TODO add your handling code here:

        try {
            String t = (String) FilterCombo.getSelectedItem();
            IFNDB.showOrders((String) IdClienteCombo.getSelectedItem(), t, table, ClienteCheck.isSelected());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }// GEN-LAST:event_BTNVisualizzaActionPerformed

    private void FilterComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FilterComboActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_FilterComboActionPerformed

    private void IdClienteComboMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_IdClienteComboMouseClicked
        // TODO add your handling code here:

    }// GEN-LAST:event_IdClienteComboMouseClicked

    private void ClienteCheckActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ClienteCheckActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ClienteCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameOrdini.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameOrdini.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameOrdini.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameOrdini.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatLightLaf.setup(); //look and feel setup
                new FrameOrdini().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNElimina;
    public javax.swing.JButton BTNVisualizza;
    private javax.swing.JCheckBox ClienteCheck;
    private javax.swing.JComboBox<String> FilterCombo;
    private javax.swing.JComboBox<String> IdClienteCombo;
    private javax.swing.JLabel IdclienteLB1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
